/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XanshaRouteImport } from './routes/xansha'
import { Route as NomaddocsRouteImport } from './routes/nomaddocs'
import { Route as IndexRouteImport } from './routes/index'

const XanshaRoute = XanshaRouteImport.update({
  id: '/xansha',
  path: '/xansha',
  getParentRoute: () => rootRouteImport,
} as any)
const NomaddocsRoute = NomaddocsRouteImport.update({
  id: '/nomaddocs',
  path: '/nomaddocs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nomaddocs': typeof NomaddocsRoute
  '/xansha': typeof XanshaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nomaddocs': typeof NomaddocsRoute
  '/xansha': typeof XanshaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nomaddocs': typeof NomaddocsRoute
  '/xansha': typeof XanshaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nomaddocs' | '/xansha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nomaddocs' | '/xansha'
  id: '__root__' | '/' | '/nomaddocs' | '/xansha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NomaddocsRoute: typeof NomaddocsRoute
  XanshaRoute: typeof XanshaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xansha': {
      id: '/xansha'
      path: '/xansha'
      fullPath: '/xansha'
      preLoaderRoute: typeof XanshaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nomaddocs': {
      id: '/nomaddocs'
      path: '/nomaddocs'
      fullPath: '/nomaddocs'
      preLoaderRoute: typeof NomaddocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NomaddocsRoute: NomaddocsRoute,
  XanshaRoute: XanshaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
